<?php

namespace GenAI\Property\Util;

use GenAI\Property\Property\Definition;

/**
 * Stateless helper that compiles the config + class bindings into plain PHP
 * source — a file that registers each Property as a container bean.
 *
 * Normally you do not call this directly: PropertyRegister::dump() /
 * dumpToFile() drive it. The whole config is emitted once as a $properties
 * array; each Property class gets a container factory that calls bindData() with
 * the slice it points at — $properties[file][group][prefix]. The file has the
 * same shape as the di container dump, so the runtime loads it with
 * Container::loadCompiled() and Properties resolve like any other bean.
 *
 * Generated output (PHP 5.3-safe) looks like:
 *
 *   <?php
 *   return function (\GenAI\Container\Container $container) {
 *       $properties = array(
 *           'app.ini' => array(
 *               'database' => array(
 *                   'app' => array('name' => 'PujaCMS', 'version' => '1.0.0'),
 *               ),
 *           ),
 *       );
 *
 *       $container->register('AppProperty', function (\GenAI\Container\Container $c) use ($properties) {
 *           $object = new \AppProperty();
 *           $object->bindData(\GenAI\Property\Util\Map::at($properties, array('app.ini', 'database', 'app')));
 *           return $object;
 *       });
 *   };
 *
 * Map::at() navigates the path safely, so a missing group/prefix yields an
 * empty Map rather than an undefined-index error.
 *
 * Compatible with PHP 5.3.29.
 */
class Dumper
{
    /**
     * Compile config + bindings to PHP source for a populate-the-loader file.
     *
     * @param array        $config      The full loaded config (file => ...).
     * @param Definition[] $definitions Class bindings, keyed by class name.
     * @return string PHP source, starting with "<?php", returning a Closure.
     */
    public static function dump($config, $definitions)
    {
        $body = array();
        foreach ($definitions as $definition) {
            $body[] = self::dumpBinding($definition);
        }

        $lines = array();
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'namespace Cache;';
        $lines[] = '';
        $lines[] = '// Generated by GenAI\\Property\\Util\\Dumper - do not edit by hand.';
        $lines[] = '// Cache\\Properties::loadInto($container) registers each bound Property as a bean.';
        $lines[] = '';
        $lines[] = 'class Properties';
        $lines[] = '{';
        $lines[] = '    public static function loadInto(\\GenAI\\Container\\Container $container)';
        $lines[] = '    {';
        $lines[] = '        $properties = ' . var_export($config, true) . ';';
        $lines[] = '';
        if (!empty($body)) {
            $lines[] = implode("\n", $body);
        }
        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Render one `$container->register(...)` factory that builds a Property and
     * binds the slice of $properties it points at. The bean id is the class name,
     * so a service or #[Bean] method can type-hint the Property and get it injected.
     *
     * @param Definition $definition
     * @return string
     */
    private static function dumpBinding(Definition $definition)
    {
        $class = $definition->getClass();

        return '    $container->register(' . var_export($class, true) . ', function (\\GenAI\\Container\\Container $c) use ($properties) {' . "\n"
             . '        $object = new \\' . ltrim($class, '\\') . '();' . "\n"
             . '        $object->bindData(\\GenAI\\Property\\Util\\Map::at($properties, ' . self::pathArray($definition) . '));' . "\n"
             . '        return $object;' . "\n"
             . '    });';
    }

    /**
     * Build the path array literal for a definition — array(file, group, prefix),
     * including only the parts that are set. Fed to Map::at($properties, ...).
     *
     * @param Definition $definition
     * @return string
     */
    private static function pathArray(Definition $definition)
    {
        $segments = array();

        if ($definition->getFile() !== null) {
            $segments[] = var_export($definition->getFile(), true);
        }
        if ($definition->getGroup() !== null) {
            $segments[] = var_export($definition->getGroup(), true);
        }
        if ($definition->getPrefix() !== null) {
            $segments[] = var_export($definition->getPrefix(), true);
        }

        return 'array(' . implode(', ', $segments) . ')';
    }
}
